export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const DELETE_ALL_FLASH_MESSAGE = 'DELETE_ALL_FLASH_MESSAGE';

export const FILE_UPLOAD_PENDING = "FILE_UPLOAD_PENDING" ;
export const FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS" ;
export const FILE_UPLOAD_ERROR = "FILE_UPLOAD_ERROR";

export const FORM_SUBMIT_PENDING = "FORM_SUBMIT_PENDING";
export const FORM_SUBMIT_SUCCESS = "FORM_SUBMIT_SUCCESS";
export const FORM_SUBMIT_ERROR = "FORM_SUBMIT_ERROR";

export const FETCH_QUIZ_LOADING = 'FETCH_QUIZ_LOADING';
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
export const FETCH_QUIZ_ERROR = 'FETCH_QUIZ_ERROR';

export const FETCH_ANSWERS_LOADING = 'FETCH_ANSWERS_LOADING';
export const FETCH_ANSWERS_SUCCESS = 'FETCH_ANSWERS_SUCCESS';
export const FETCH_ANSWERS_ERROR = 'FETCH_ANSWERS_ERROR';

export const QUIZ_LIST_LOADING = 'QUIZ_LIST_LOADING';
export const QUIZ_LIST_SUCCESS = 'QUIZ_LIST_SUCCESS';
export const QUIZ_LIST_ERROR = 'QUIZ_LIST_ERROR';